### ISSUE TITLE
Sending out 2nd CFP

### ISSUE THREAD

**Issue by j0ma** [sigturk/sigturk#109]
Details for sending out 2nd CFP

```[tasklist]
# Tasks
- [ ] Research institutes affiliated with Turkish universities
- [ ] TurkLang conference
- [ ] Departmental mailing lists
- Slack groups
    - [x] low-resource-languages
    - [x] ACL with Love
- Telegram groups
    - [x] Turkic Interlingua
    - [x] Kod Odin
    - [x] SIGTURK
```

**Comment by j0ma** [comment]
@varie Can you handle Kod Odin?
@mehmetoguzderin Do you know any research institutes would be good to send the CFP to?

**Comment by mehmetoguzderin** [comment]
I was pondering about this matter. I believe that it might be better for the subsequent execution of workshop to send out notice with more significant AoT and reach out to these institutes offering translation services, doing both translation for novel research from their network and re-publication of their significant works or summaries (in similar vein to publishing already public works), where things can be computationally relevant by linguistic treatment or significant data. In that light, although I have certain candidate places to just try to reach out, I think given the disconnect, it might be better to think of this one as something to carry over for the next workshop than the one at hand, and get the basics right with this one. Thanks!

**Comment by mehmetoguzderin** [comment]
This was done, closing the issue

**Comment by mehmetoguzderin** [comment]
Oops, wrong issue

**Comment by varie** [comment]
> Details for sending out 2nd CFP
> 
> ```
> # Tasks
> - [ ] Research institutes affiliated with Turkish universities
> - [ ] TurkLang conference
> - [ ] Departmental mailing lists
> - Slack groups
>     - [x] low-resource-languages
>     - [x] ACL with Love
> - Telegram groups
>     - [x] Turkic Interlingua
>     - [x] Kod Odin
>     - [x] SIGTURK
> ```

I have sent it to Kod Odin and marked it in the issue.

**Comment by j0ma** [comment]
@d-ataman can you send to corpora-list?

**Comment by j0ma** [comment]
Merging #116 into this

**Comment by j0ma** [comment]
I will check what happened re: corpora-list

**Comment by j0ma** [comment]
This is now done, thanks @d-ataman !
